**NumPy**, stands for Numerical Python
Using NumPy, mathematical and logical operations on arrays can be performed 

**Arrays**
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. 

In [ ]:
#one dimensionalarray
import numpy as np 
n = np.array([1,2,3]) 
print(n)

[1 2 3]


In [ ]:
#2 dimensional array
a = np.array([[1, 2], [3, 4]]) 
print(a)


[[1 2]
 [3 4]]


In [ ]:
 #dtype parameter 
import numpy as np 
a = np.array([1, 2, 3], dtype ='str') 
print(a)

['1' '2' '3']


**ARRAY ATTRIBUTES**

shape

ndim




In [ ]:
#shape
import numpy as np 
a = np.array([[1,2,3],[4,5,6]])
print(a) 
print (a.shape)
print(a.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [ ]:
# resizing of ndarray 
import numpy as np 

a = np.array([[1,2,3],[4,5,6]]) 
print(a)
a.shape = (3,2) 
print(a)
print(a.ndim)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
2


In [ ]:
#reshape
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
print(a)
print(a.reshape(3,2)) 
#print(b)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#ndim
# this is one dimensional array 
import numpy as np 
a = np.arange(24)
print(a)
print(a.ndim)  
 
# now reshape it 
b = a.reshape(4,2,3) 
print(b)
print(b.ndim)
# b is having three dimensions

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]
3


In [ ]:
d=np.arange(30) #got 30 num
a=(d.ndim)#find dimension
print(a)
print(d)
d.reshape(5,2,3) #reshape the first array to 5 r,6c   
       

1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29]]])

In [ ]:
type(d)

numpy.ndarray

In [ ]:
e=np.zeros((3,4))
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
o=np.ones((3,4))*3
o

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [ ]:
u=np.ones((3,4))
u

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
f=np.arange(10).reshape(5,3)

ValueError: ignored

In [ ]:
f=np.arange(15).reshape(5,3)
print(f)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


* **vstack**
stacking of arrays


In [ ]:
v=np.arange(9).reshape(3,3)
v

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
s=np.arange(12).reshape(4,3)
s

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a=np.arange(10).reshape(5,2)
print(a)
np.vstack((v,a))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


ValueError: ignored

In [ ]:
np.vstack((v,s))#column values should be same for stacking

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

**generate random number and create an array**

In [ ]:
 
np.random.random()#generates a random num (0-1)

0.3978058458216427

In [ ]:
np.random.randint(low=2,high=10,size=5)
#out_arr = geek.random.randint(low = 0, high = 3, size = 5) 

array([4, 9, 4, 5, 2])

In [ ]:
import numpy as np

In [ ]:
k=np.random.random((2,5))
k

array([[0.63443314, 0.12349967, 0.6393049 , 0.85531814, 0.98585512],
       [0.15268544, 0.97875884, 0.87686818, 0.46290352, 0.76626227]])

In [ ]:
m=np.floor(k)#here only 0 as it is the nearest integer
m


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
c=np.ceil(k)#round to the nearest highest value
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
r=np.floor(10*k) #multiply by 10 
r

array([[6., 1., 6., 8., 9.],
       [1., 9., 8., 4., 7.]])

**1.find coying an array**
2.find vsplit and hsplit

In [ ]:
#copying
x=np.array([2,3,5,6])
x

array([2, 3, 5, 6])

In [ ]:
#copying of x to y
y=x 
y#it is not creating a copy here in numpy
#it is actually creating a reference

array([2, 3, 5, 6])

In [ ]:
x

array([2, 3, 5, 6])

In [ ]:
y

array([2, 3, 5, 6])

In [ ]:
#try changing something in the first array
x[2]=66
x

array([ 2,  3, 66,  6])

In [ ]:
y#when we print y here also value has changed
#bcoz both x and y are referring to the same

array([ 2,  3, 66,  6])

In [ ]:
s=np.array([5,3,6,8])
r=s.copy()
r



array([5, 3, 6, 8])

In [ ]:
s[2]=33
s

array([ 5,  3, 33,  8])

In [ ]:
r

array([5, 3, 6, 8])

**spliting**

In [ ]:
v=np.floor(100*np.random.random((2,6)))
v

array([[ 1., 82., 25., 19.,  6., 26.],
       [80., 75., 47., 89., 15., 92.]])

In [ ]:
np.hsplit(v,3)

[array([[ 1., 82.],
        [80., 75.]]), array([[25., 19.],
        [47., 89.]]), array([[ 6., 26.],
        [15., 92.]])]

In [ ]:
np.vsplit(v,2)

[array([[ 1., 82., 25., 19.,  6., 26.]]),
 array([[80., 75., 47., 89., 15., 92.]])]

In [ ]:
q=np.floor(100*np.random.random((8,2)))
q

array([[80., 84.],
       [45.,  0.],
       [97., 63.],
       [44., 89.],
       [76., 84.],
       [57., 75.],
       [36., 79.],
       [89.,  5.]])

In [ ]:
np.vsplit(q,2)

[array([[80., 84.],
        [45.,  0.],
        [97., 63.],
        [44., 89.]]), array([[76., 84.],
        [57., 75.],
        [36., 79.],
        [89.,  5.]])]